#include "Valdez_1DExer1.h"
#include "Valdez_1DExer2.h"
#include "Valdez_1DExer3.h"
#include "Valdez_1DExer4.h"
#include "Valdez_1DExer5.h"
#include "Valdez_1DExer6.h"
#include "Valdez_1DExer7.h"
#include "Valdez_1DExer8.h"
#include "Valdez_1DExer9.h"

#include "Valdez_2D.h"